services:
  postgres:
    image: postgres:15-alpine
    container_name: poker-postgres
    environment:
      POSTGRES_DB: poker_game
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - poker-network

  redis:
    image: redis:7-alpine
    container_name: poker-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - poker-network

  master-server:
    build:
      context: .
      dockerfile: tools/docker/master-server.Dockerfile
    container_name: poker-master
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/poker_game
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=your-super-secret-jwt-key
      - MASTER_SERVER_PORT=3001
    ports:
      - "3001:3001"
    depends_on:
      - postgres
      - redis
    networks:
      - poker-network
    restart: unless-stopped

  dedicated-server-1:
    build:
      context: .
      dockerfile: tools/docker/dedicated-server.Dockerfile
    container_name: poker-dedicated-1
    environment:
      - NODE_ENV=production
      - MACHINE_ID=1
      - SERVER_ID=poker-server-1
      - REDIS_URL=redis://redis:6379
      - MASTER_SERVER_URL=http://master-server:3001
      - DEDICATED_SERVER_PORT=3002
    ports:
      - "3002:3002"
    depends_on:
      - master-server
    networks:
      - poker-network
    restart: unless-stopped

  dedicated-server-2:
    build:
      context: .
      dockerfile: tools/docker/dedicated-server.Dockerfile
    container_name: poker-dedicated-2
    environment:
      - NODE_ENV=production
      - MACHINE_ID=2
      - SERVER_ID=poker-server-2
      - REDIS_URL=redis://redis:6379
      - MASTER_SERVER_URL=http://master-server:3001
      - DEDICATED_SERVER_PORT=3002
    ports:
      - "3003:3002"
    depends_on:
      - master-server
    networks:
      - poker-network
    restart: unless-stopped

  ai-server:
    build:
      context: .
      dockerfile: tools/docker/ai-server.Dockerfile
    container_name: poker-ai
    environment:
      - NODE_ENV=production
      - REDIS_URL=redis://redis:6379
      - AI_SERVER_PORT=3003
      - AI_WORKER_COUNT=4
    ports:
      - "3004:3003"
    depends_on:
      - redis
    networks:
      - poker-network
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: poker-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./tools/docker/nginx.conf:/etc/nginx/nginx.conf
      - ./apps/web-client/dist:/usr/share/nginx/html
    depends_on:
      - master-server
    networks:
      - poker-network
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:

networks:
  poker-network:
    driver: bridge
